---
title: "Poverty"
author: "Dae Hyun Lee"
date: "10/20/2019"
output: pdf_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(magrittr)
library(esquisse)
library(gridExtra)
library(shiny)
library(AER)
```

# Get Data

wbstats
```{r}
library(wbstats)
new_wb_cache <- wbcache()
```
WDI
```{r}
library(WDI)
new_wdi_cache <- WDIcache()
```
Next we find out the IDs for the indicators we are intersted in: GDP, life expectancy, and infant mortality.
_wb_
```{r}
wbsearch("gdp.*capita.*US\\$", cache = new_wb_cache)
wbsearch("life expectancy at birth.*total", cache = new_wb_cache)
wbsearch("^mortality.*rate.*infant", cache = new_wb_cache)
```
_WDI_
```{r}
WDIsearch("gdp.*capita.*US\\$", cache = new_wdi_cache)
WDIsearch("life expectancy at birth.*total", cache = new_wdi_cache)
WDIsearch("^mortality.*rate.*infant", cache = new_wdi_cache)
```

wbstats
```{r}
wb_dat <- wb(indicator = c("NY.GDP.PCAP.KD", "SP.DYN.LE00.IN", "SP.DYN.IMRT.IN")) 
names(wb_dat)
```
WDI
```{r}
wdi_dat <- WDI(indicator = c("NY.GDP.PCAP.KD", "SP.DYN.LE00.IN", "SP.DYN.IMRT.IN"), start = 1960, end = 2015, extra = TRUE)
names(wdi_dat)
```
Clean up
_wb_
```{r}
wb_countries <- wbcountries() 
names(wb_countries)
wb_dat <- merge(wb_dat, y = wb_countries[c("iso2c", "region")], by = "iso2c", all.x = TRUE) 
wb_dat <- subset(wb_dat, region != "Aggregates")
```
_WDI_
```{r}
wdi_dat <- subset(wdi_dat, region != "Aggregates")
```
rename the indicators
_wb_
```{r}

wb_dat$indicatorID[wb_dat$indicatorID == "NY.GDP.PCAP.KD"] <- "GDP" 
wb_dat$indicatorID[wb_dat$indicatorID == "SP.DYN.LE00.IN"] <- "life_expectancy" 
wb_dat$indicatorID[wb_dat$indicatorID == "SP.DYN.IMRT.IN"] <- "infant_mortality"
library(reshape2)
wb_dat <- dcast(wb_dat, iso2c + country + date + region ~ indicatorID, value.var = 'value')

```
WDI
```{r}

names(wdi_dat)[which(names(wdi_dat) == "NY.GDP.PCAP.KD")] <- "GDP" 
names(wdi_dat)[which(names(wdi_dat) == "SP.DYN.LE00.IN")] <- "life_expectancy" 
names(wdi_dat)[which(names(wdi_dat) == "SP.DYN.IMRT.IN")] <- "infant_mortality"

```

Plot a graph

wbstats
```{r}
library(ggplot2)
ggplot(subset(wb_dat, date == "2008"), aes(x = GDP, y = infant_mortality)) + geom_point()
```
WDI
```{r}
ggplot(subset(wdi_dat, year == 2008), aes(x = GDP, y = infant_mortality)) + geom_point()
```

Reproduce graph from the paper
Life expectancy
```{r}
lifexp_countries <- subset(wb_dat, country %in% 
                             c("United States", "Rwanda", "Mongolia", "Pakistan", "Lao PDR", "Bhutan", "Malaysia", "Brazil", "Ireland", "Japan", "Sweden", "Netherlands"))
ggplot(subset(lifexp_countries, date == "2008"), aes(x = GDP, y = life_expectancy, color = country == "United States")) +
geom_point() +
geom_text(aes(label = country), size=3, nudge_y = 0.4) + scale_x_continuous(limits = c(0, 70000))
```
Infant Mortality
```{r}
infmort_countries <- subset(wb_dat, country %in% c("United States", "Tonga", "Colombia", "Grenada", "Sri Lanka", "Malta", "Germany", "Japan", "Sweden", "Netherlands"))
ggplot(subset(infmort_countries, date == "2008"), aes(x = GDP, y = infant_mortality, color = country == "United States")) +
geom_point() +
geom_text(aes(label = country), size=3, nudge_y = 0.2) + scale_x_continuous(limits = c(0, 70000))
```


Simple Interactivity
```{r}
library(plotly)
g <- ggplot(subset(infmort_countries, date > "1999" & date <= "2015"), aes(x = GDP, y = infant_mortality, color = country == "United States", tooltip = country)) +
geom_point() +
facet_wrap(~ date) + theme(legend.position="none")
ggplotly(g)
```

